import "@bobaboard/boba-editor/dist/main.css";

import Editor, { EditorContext } from "@bobaboard/boba-editor";
import type { GetStaticProps, NextPage } from "next";

import Head from "next/head";
import styles from "../styles/Home.module.css";

const REMOTE_EMBEDS_URL = `https://boba-embeds.herokuapp.com/iframely`;
const getOEmbedFromUrl = (url: string) => {
  // We add a random number to the embed load to get around https://github.com/itteco/iframely/issues/281
  return fetch(`${REMOTE_EMBEDS_URL}?url=${url}&random=${Math.random()}`).then(
    (response) => response.json()
  );
};

const Home: NextPage = ({ posts }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://platform.twitter.com/widgets.js"
          charSet="utf-8"
          defer
        ></script>
      </Head>

      <main className={styles.main}>
        <EditorContext.Provider
          value={{
            fetchers: {
              getOEmbedFromUrl,
            },
          }}
        >
          {posts.map((post: any) => (
            <article className={styles.article}>
              <Editor key={post.id} initialText={JSON.parse(post.content)} />
            </article>
          ))}
        </EditorContext.Provider>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  const response = await fetch(
    "https://backend-dot-bobaboard.uc.r.appspot.com/threads/1a80732d-82ae-4173-b5c5-7d350e9b7caa"
  );

  const data = await response.json();
  const posts = data.posts.map((post: any) => ({
    id: post.id,
    content: post.content,
    author: post.secret_identity.name,
  }));
  return {
    props: {
      posts,
    },
  };
};
